# do not change these lines: 'parameters' and 'languages'
parameters:
    languages:
        en:
            name: English
            title: English
            prefix: en
            enabled: 1
        ge:
            name: Georgian
            title: ქართული
            prefix: ge
            enabled: 1

    languages.locales: [en, ge]
    languages.default: en